### ISSUE TITLE
"clean existing gluster deployment" doesn't remove filter from lvm.conf

### ISSUE THREAD

**Issue by derekm** [oVirt/cockpit-ovirt#8]
After cleaning up a gluster deployment that has gone awry, you cannot recreate the same gluster deployment without deleting `filter=` lines from `/etc/lvm/lvm.conf` on all nodes.

**Comment by derekm** [comment]
This blog accelerated my ability to fix this situation: https://blog.wefixit.at/ovirt-node-4-4-gluster-installation-failed-with-device-dev-sdb-excluded-by-a-filter/

**Comment by sandrobonazzola** [comment]
Moved to bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1953921
